### ISSUE TITLE
Request permission for some localization work

### ISSUE THREAD

**Issue by knightli** [war3i4i/LastEpochImprovements#3]
Thank you for writing such a great and convenient Mod. 

Among the fans of the LE game on the Chinese Internet, many friends love your Mod, but it is not very convenient to use due to language reasons. 

I would like to know if I can get your permission, allowing me to do localization work and do some optimizations in terms of display.

Thanks again and hope to hear from you soon.

**Comment by war3i4i** [comment]
Yeah sure. I have no problems with that. Just send me the link on mod you post so I can read comments and so on after :D
